# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapKit_and_Then' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapKit_and_Then

pod 'Then'
pod 'SnapKit'

end
